#! /bin/bash

set -e

DATABASE="User_Profiles"
MYSQL="mysql -uroot -e"

# Cleaning up database
echo "Dropping exisitng database and re-creating ..."
${MYSQL}"DROP DATABASE IF EXISTS ${DATABASE}"
${MYSQL}"CREATE DATABASE ${DATABASE}"
${MYSQL}"USE ${DATABASE}; CREATE TABLE profiles (id INT NOT NULL PRIMARY KEY AUTO_INCREMENT, username VARCHAR(25), password VARCHAR(40), email VARCHAR(30), phone VARCHAR(20))"

BACKUP="/home/vagrant/${DATABASE}.sql"

# Restore backup and sanitize data
echo "Restoring backup ..."
echo ${DATABASE}
mysql -uhudl -pdemo ${DATABASE} < ${BACKUP}

# Clean data for dev
echo "Sanitizing data ..."
${MYSQL}"USE User_Profiles; UPDATE profiles SET email = CONCAT('player', id, '@example.com'), phone = CONCAT('12', id, '-', '123', '-', '6789'), password = md5('admin');"
