#! /bin/bash

##########################################################################
#
# NAME: dotprod.sh
# DATE: 5/11/2015
# AUTHOR: Orlando Morriesette <o.morriesette1@gmail.com>
# VERSION: 1.0
# DESCRIPTION: This program configures replication on a production master
#              and slave. It also allows you to enter database entries,
#              verify those entries, and back up the data for a dev 
#	       environment
#
##########################################################################

set -e

# Set Global Variables
MYSQL="mysql -uroot -e"
REPINFO="/home/vagrant/repinfo"

# Usage
SCRIPT=$(basename $0)
usage() {
    cat << 'EOF'

    Usage: ${SCRIPT} [OPTIONS]

    This script will setup database replication and enable periodic backups.

    OPTIONS:
          -s, : Start the replication setup
          -i, : Insert a new entry in the master database
          -v, : Verify the last 5 rows in the database
          -b, : Backup data on the slave and auto restore on the dev machine (scrubbed)
  -h, --help  : Display this help message

EOF
exit 1;
}


# Begin Replication Setup
start(){
    # On Master configure replication
    echo "Configuring replication on master ..."
    ${MYSQL}"GRANT REPLICATION SLAVE ON *.* TO hudl@192.168.50.20 IDENTIFIED BY 'demo'"
    ${MYSQL}"FLUSH PRIVILEGES"
    ${MYSQL}"USE User_Profiles"
    ${MYSQL}"FLUSH TABLES WITH READ LOCK"
    ${MYSQL}"SHOW MASTER STATUS"
	     
    # Refresh mysqld
    sudo service mysqld restart

    # Gather necessary info for replication and send to slave
    ${MYSQL}"SHOW MASTER STATUS" | grep my | awk '{print $1}' > $REPINFO
    ${MYSQL}"SHOW MASTER STATUS" | grep my | awk '{print $2}' >> $REPINFO

    if [ -f $REPINFO ]; then
	scp $REPINFO prod-slave:~
    else
	echo "$REPINFO does not exist" 
	exit 1;
    fi

    # On Slave configure replication
    ssh prod-slave "bash ~/slave/demo-slave"
}


# Method for adding entries into the database
insert(){
shift 
if [ $# -ne 4 ]; then
# Usage
    echo ""
    echo "Usage: ${SCRIPT} --insert "NAME" "PASS" "EMAIL" "PHONE""
    echo ""
    exit 1;
else

    local _name=$1
    local _pass=$2
    local _email=$3
    local _phone=$4

    echo
    echo "INSERT INTO profiles (id, username, password, email, phone) VALUES ($_name, $_pass, $_email, $_phone)"
    
    ${MYSQL}"Use User_Profiles; INSERT INTO profiles (id, username, password, email, phone) VALUES
    (NULL,'$_name', SHA1('$_pass'), '$_email', '$_phone')"
fi

if [ $? == "0" ];then
    echo
    echo "Database INSERT successful!"
fi
}


# Verify Master and Server is replicating
verify(){
echo
echo "====== MASTER DATABASE ======"
${MYSQL}"USE User_Profiles; SELECT * FROM profiles ORDER by ID ASC LIMIT 0,5"
echo 
echo

echo "====== SLAVE DATABASE ======"
ssh prod-slave "mysql -uroot -e 'USE User_Profiles; SELECT * FROM profiles ORDER by ID ASC LIMIT 0,5'"
echo

echo
ssh prod-slave "ssh hudl-dev verify_db"
echo 
}


backup(){
echo "Running backup on slave server ..."
ssh prod-slave ~/slave/hourly-backup
}


case "$1" in
	    -s) start
		;;
	    -i) insert "$@"
                ;;
	    -v) verify $@
		;;
	    -b) backup
		;;
     -h|--help) usage
                ;;
             *) usage
                ;;
esac
