#!/bin/bash

MYSQL="mysql -uroot -e"
REPINFO="/home/vagrant/repinfo"

# Begin replication process on master
MASTER_LOG=$(sed -n '1p' ${REPINFO})
MASTER_POS=$(sed -n '2p' ${REPINFO})

echo "$MASTER_LOG"
echo "$MASTER_POS"

${MYSQL}"CHANGE MASTER TO MASTER_HOST='prod-master', MASTER_USER='hudl', MASTER_PASSWORD='demo', MASTER_LOG_FILE='${MASTER_LOG}', MASTER_LOG_POS=${MASTER_POS}"

sudo service mysqld restart

${MYSQL}"slave start"
${MYSQL}"show slave status\G"
