#! /bin/bash

# Backup data and restore to dev machine
echo "Backing up database ..."
mysqldump -uhudl -pdemo --database User_Profiles > ~/backups/User_Profiles.sql

scp ~/backups/User_Profiles.sql hudl-dev:~
ssh hudl-dev ~/dev/restore-backup

# Restart mysql services
sudo service mysqld start
